# Generated by Django 5.0.1 on 2024-03-16 10:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mywayapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userstats',
            name='badge',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='people_with_similar_badges', to='mywayapp.badge'),
        ),
        migrations.AlterField(
            model_name='userstats',
            name='conditions',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='people_with_similar_conditions', to='mywayapp.condition'),
        ),
        migrations.AlterField(
            model_name='userstats',
            name='hobbies',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='people_with_similar_hobbies', to='mywayapp.hobby'),
        ),
        migrations.AlterField(
            model_name='userstats',
            name='isverified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='userstats',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='people_within_same_region', to='mywayapp.location'),
        ),
    ]
