# Generated by Django 5.0.1 on 2024-03-16 19:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mywayapp', '0002_alter_userstats_badge_alter_userstats_conditions_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='community',
            name='related_condition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='communities_related_to_condition', to='mywayapp.condition'),
        ),
    ]
